version: '3'
services: 
  php-apache:
    container_name: php-apache
    build: 
      context: ./
      dockerfile: php.Dockerfile
    restart: always
    volumes: 
      - ./DocumentRoot:/var/www/html
    links:
      - 'mysqlserver'
    networks: 
      - 'backend'
  mysqlserver:
    container_name: mysqlserver
    build: 
      context: ./
      dockerfile: mysql.Dockerfile
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks: 
      - 'backend'
    environment:
      TZ: "Europe/Warsaw"
  apache:
    container_name: apache
    build:
      context: ./
      dockerfile: apacheHttpd.Dockerfile
    restart: always
    networks: 
      - 'backend'
      - 'frontend'  
    depends_on: 
      - php-apache
      - mysqlserver
    ports: 
      - 6666:80
    volumes: 
      - ./DocumentRoot:/usr/local/apache2/htdocs/
volumes: 
  database:
networks:
  backend:
  frontend: